#!/usr/bin/env python3
"""Generate realistic production traffic so Module 3 has something to monitor.

    python scripts/generate_traffic.py                    # 40 runs over 10 minutes
    python scripts/generate_traffic.py --minutes 10 --runs 40
    python scripts/generate_traffic.py --burst            # all at once (charts look wrong)
    python scripts/generate_traffic.py --dry-run          # print the plan, call nothing
    python scripts/generate_traffic.py --engine-warmup    # RUN THIS 24h BEFORE THE SESSION

WHY SPREAD IT OVER TIME
-----------------------
Monitoring in a demo environment is boring for a specific, fixable reason: 40 traces created
in 40 seconds are one spike. LangSmith's shortest window is the last hour, and that view
buckets by minute, so traffic spread over ~10 minutes gives you an actual time series with
shape: a latency trend, an error rate that moves, a cost line that climbs.

That is the difference between "here is a chart" and "here is a chart you can read." Start
this at the beginning of Module 3 and let it run in the background while you talk; by the
time you open the dashboard there are ten minutes of history waiting.

WHAT IT SENDS
-------------
A realistic mix, not just happy paths. Roughly:

    55%  ordinary work        procedures, equipment, tank levels
    15%  the OSHA-style probe THE POINT. ARIA answers regulatory questions from memory
                              because of the deliberate gap in its prompt. These are the
                              traces Module 3's online evaluator flags and Module 4 fixes.
    10%  tool failures        injected errors, so error rate is non-zero and honest-failure
                              behavior is visible in the traces
    10%  write requests       work orders, including under-specified ones
     5%  ambiguous input      "P-101", "tank 42", "the crude pump"
     5%  out of scope         obvious off-topic

Every run is tagged and carries metadata (`persona`, `channel`, `traffic_generator=true`) so
you can filter it apart from traffic the room generated by hand in the front end. Keeping
those distinguishable matters. Module 4's annotation queue should review what *people*
asked, not what this script asked.

ENGINE WARM-UP  (--engine-warmup)  -- RUN THIS THE DAY BEFORE
-------------------------------------------------------------
LangSmith Engine scans each connected project **every 6 hours** and clusters traces into
*recurring* issues. Two consequences for a workshop:

  1. There is no live demo. Traffic sent during the session will not have been scanned yet.
  2. One instance of a failure is not a pattern. Engine is looking for recurrence, so a
     handful of scattered failures may not cluster into anything.

`--engine-warmup` sends a high-volume, deliberately *repetitive* batch: many instances of the
same few failure shapes, so each one is unmistakably a pattern rather than a one-off. Those
shapes are chosen to line up with Engine's own issue categories:

    out_of_library      -> Hallucination / Guardrail bypass
    tool_failure        -> Silent tool error / Failed error recovery
    ambiguous           -> Incorrect tool args / Wrong tool
    write (vague)       -> Feature gap / Flawed plan

Run it the evening before, against the project you will demo from:

    LANGSMITH_PROJECT=aria-production python scripts/generate_traffic.py --engine-warmup

Then during the session, send normal traffic for the monitoring charts and let Engine show
what it found overnight.

IT WRITES TO THE PRODUCTION PROJECT
-----------------------------------
Defaults to `$LANGSMITH_PROJECT`, which should be your production project and NOT the project
your experiments write to. Mixing them ruins both: your production error rate gets polluted by
deliberately-failing eval runs, and your experiment history gets buried in live traffic.
"""

from __future__ import annotations

import argparse
import asyncio
import os
import random
import sys
import time
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))


@dataclass(frozen=True, slots=True)
class Request:
    question: str
    persona: str
    category: str
    #: Tool name -> mocked failure. None means real tools.
    inject_failure: str | None = None


# --------------------------------------------------------------------------- the mix

ORDINARY = [
    "What's the lockout procedure for P-101A?",
    "What do I need before pulling the seal on P-101A?",
    "Is nitrogen purge required before entering V-205?",
    "What's the level in tank 42?",
    "What's the current status of K-501?",
    "When is the next PM due on P-311?",
    "What procedures apply to V-206?",
    "What's the fire watch requirement for hot work?",
    "Do I need a positive blind to enter C-402?",
    "What PPE does line breaking require on H2S service?",
    "What's the level in tank 43?",
    "Which unit is E-118 in?",
    "What's the H2S response if my monitor alarms at 12 ppm?",
    "How do I verify zero energy before opening the pump casing?",
    "What equipment is in the Naphtha Hydrotreater?",
]

#: ★ The probe. ARIA answers these from parametric memory because of the deliberate gap in
#: its system prompt. Verified live: it states the benzene PEL as 1 ppm TWA / 5 ppm STEL with
#: no source at all. These are the traces Module 3 catches and Module 4 turns into a test.
OUT_OF_LIBRARY = [
    "What's the OSHA permissible exposure limit for benzene?",
    "What's the max allowable working pressure for a 300# flange in 340F crude service?",
    "What's the LEL for hydrogen sulfide?",
    "How many air changes does API recommend before vessel entry?",
    "What's the NFPA 704 rating for crude oil?",
    "What torque should a 1-inch B7 stud take on a gasketed flange?",
]

AMBIGUOUS = [
    "What do I need to do before pulling the seal on P-101?",
    "What's the level in tank 42?",
    "Tell me about the crude charge pump.",
    "Is the amine drum available for entry?",
]

WRITES = [
    "Raise an urgent work order on P-101A, inboard seal leaking to atmosphere. I'm T. Alvarez.",
    "Create a work order for a vibration survey on P-311. Requested by J. Coad.",
    "P-311 is making a weird noise. Can you raise a work order for it? I'm J. Coad.",
    "File a routine work order on K-501 for valve inspection.",
    "Take P-101A out of service, the seal is shot.",
]

OFF_TOPIC = [
    "What's a good recipe for brisket?",
    "Can you help me draft a performance review for my tech?",
    "What's the weather going to do this afternoon?",
]

FAILURE_TARGETS = ["search_procedures", "get_equipment", "get_tank_status", "create_work_order"]

PERSONAS = ["day_shift_tech", "night_shift_operator", "unit_supervisor", "planner", "contractor"]
CHANNELS = ["mobile", "control_room", "desktop"]


def build_engine_warmup_plan(runs: int = 120, seed: int = 11) -> list[Request]:
    """A repetitive, failure-heavy mix so Engine has genuine patterns to cluster.

    Deliberately NOT a realistic traffic profile. Realistic traffic is what you want for the
    monitoring charts; this is what you want for issue detection, and they are different jobs.
    Engine is looking for *recurrence*, so we send the same few failure shapes many times over
    rather than a broad sample of everything.
    """
    rng = random.Random(seed)
    plan: list[Request] = []

    # ~35% the same regulatory-memory failure, drawn from a small pool so each specific
    # question repeats several times. That repetition is the signal.
    for _ in range(round(runs * 0.35)):
        plan.append(Request(rng.choice(OUT_OF_LIBRARY[:3]), rng.choice(PERSONAS), "out_of_library"))

    # ~25% silent tool errors, concentrated on two tools so the pattern is per-tool.
    for _ in range(round(runs * 0.25)):
        plan.append(
            Request(
                rng.choice(WRITES[:3]),
                rng.choice(PERSONAS),
                "tool_failure",
                inject_failure=rng.choice(["create_work_order", "get_equipment"]),
            )
        )

    # ~15% ambiguous tags -> incorrect tool args / wrong tool
    for _ in range(round(runs * 0.15)):
        plan.append(Request(rng.choice(AMBIGUOUS), rng.choice(PERSONAS), "ambiguous"))

    # ~10% under-specified writes -> feature gap / flawed plan
    for _ in range(round(runs * 0.10)):
        plan.append(Request(WRITES[2], rng.choice(PERSONAS), "write"))

    # The remainder ordinary, so Engine has a healthy baseline to contrast against. An issue
    # detector with no successful traffic to compare to has a much harder job.
    while len(plan) < runs:
        plan.append(Request(rng.choice(ORDINARY), rng.choice(PERSONAS), "ordinary"))

    rng.shuffle(plan)
    return plan


def build_plan(runs: int, seed: int = 7) -> list[Request]:
    """Deterministic mix. Seeded so a facilitator can rehearse and get the same shape."""
    rng = random.Random(seed)
    plan: list[Request] = []

    counts = {
        "ordinary": round(runs * 0.55),
        "out_of_library": round(runs * 0.15),
        "tool_failure": round(runs * 0.10),
        "write": round(runs * 0.10),
        "ambiguous": round(runs * 0.05),
        "off_topic": round(runs * 0.05),
    }
    counts["ordinary"] += runs - sum(counts.values())  # absorb rounding

    for _ in range(counts["ordinary"]):
        plan.append(Request(rng.choice(ORDINARY), rng.choice(PERSONAS), "ordinary"))
    for _ in range(counts["out_of_library"]):
        plan.append(Request(rng.choice(OUT_OF_LIBRARY), rng.choice(PERSONAS), "out_of_library"))
    for _ in range(counts["tool_failure"]):
        plan.append(
            Request(
                rng.choice(ORDINARY + WRITES),
                rng.choice(PERSONAS),
                "tool_failure",
                inject_failure=rng.choice(FAILURE_TARGETS),
            )
        )
    for _ in range(counts["write"]):
        plan.append(Request(rng.choice(WRITES), rng.choice(PERSONAS), "write"))
    for _ in range(counts["ambiguous"]):
        plan.append(Request(rng.choice(AMBIGUOUS), rng.choice(PERSONAS), "ambiguous"))
    for _ in range(counts["off_topic"]):
        plan.append(Request(rng.choice(OFF_TOPIC), rng.choice(PERSONAS), "off_topic"))

    rng.shuffle(plan)
    return plan


# ------------------------------------------------------------------------ execution


async def send(request: Request, index: int, *, model: str | None = None) -> dict:
    """Run one request against ARIA, tagged so it is findable and filterable."""
    from langgraph.checkpoint.memory import InMemorySaver

    from aria.agent_v2 import build_agent
    from aria.tools import LOCAL_TOOLS
    from evals.mocking import CallRecorder, make_mock_tool

    tools = list(LOCAL_TOOLS)
    if request.inject_failure:
        # Same contract, failing body: so the trace shows a real tool error and we can watch
        # what ARIA tells the user about it.
        recorder = CallRecorder()
        failing = make_mock_tool(
            request.inject_failure,
            {
                "error": "Upstream maintenance system returned 503 Service Unavailable.",
                "recoverable": True,
            },
            recorder,
        )
        tools = [failing if t.name == request.inject_failure else t for t in tools]

    agent = build_agent(
        model=model,
        tools=tools,
        checkpointer=InMemorySaver(),
        # Unattended: nothing is watching to approve an interrupt, so it would hang forever.
        require_approval=False,
    )

    started = time.monotonic()
    try:
        result = await agent.ainvoke(
            {"messages": [{"role": "user", "content": request.question}]},
            config={
                "configurable": {"thread_id": f"traffic-{index}"},
                # Tags and metadata are what make this traffic filterable in Module 3, and
                # separable from what the room asked by hand in Module 4.
                "tags": ["traffic_generator", request.category, request.persona],
                "metadata": {
                    "traffic_generator": True,
                    "category": request.category,
                    "persona": request.persona,
                    "channel": random.choice(CHANNELS),
                    "injected_failure": request.inject_failure or "",
                },
                "run_name": f"aria:{request.category}",
            },
        )
        answer = result["messages"][-1].content
        if isinstance(answer, list):
            answer = "".join(
                b.get("text", "") for b in answer if isinstance(b, dict) and b.get("type") == "text"
            )
        return {
            "ok": True,
            "category": request.category,
            "seconds": time.monotonic() - started,
            "chars": len(str(answer)),
        }
    except Exception as exc:  # noqa: BLE001
        # A crashed run is signal, it is what makes the error-rate chart non-zero and honest.
        # Swallow it here so one failure does not stop the generator.
        return {
            "ok": False,
            "category": request.category,
            "seconds": time.monotonic() - started,
            "error": f"{type(exc).__name__}: {exc}",
        }


async def run(
    *,
    runs: int,
    minutes: float,
    burst: bool,
    model: str | None,
    concurrency: int,
    engine_warmup: bool = False,
) -> None:
    plan = build_engine_warmup_plan(runs) if engine_warmup else build_plan(runs)
    project = os.environ.get("LANGSMITH_PROJECT", "(unset)")

    if engine_warmup:
        print("MODE:      Engine warm-up (repetitive failure mix, not realistic traffic)")
        print("           Engine scans every 6h, this must land well before you present.\n")
    print(f"project:   {project}")
    print(f"runs:      {len(plan)}")
    print(f"spread:    {'BURST: all at once' if burst else f'{minutes:g} minutes'}")
    print(f"model:     {model or os.environ.get('ARIA_MODEL')}")
    print()
    for category in sorted({r.category for r in plan}):
        n = sum(1 for r in plan if r.category == category)
        print(f"  {category:<16} {n:>3}")
    print()

    if not burst and project == "(unset)":
        print("WARNING: LANGSMITH_PROJECT is unset, so these traces have nowhere useful to go.")

    gap = 0.0 if burst else (minutes * 60) / max(len(plan), 1)
    semaphore = asyncio.Semaphore(concurrency)
    results: list[dict] = []
    started = time.monotonic()

    async def worker(request: Request, index: int) -> None:
        async with semaphore:
            outcome = await send(request, index, model=model)
            results.append(outcome)
            elapsed = time.monotonic() - started
            mark = "ok " if outcome["ok"] else "ERR"
            print(
                f"  [{elapsed:6.1f}s] {mark} {outcome['category']:<16} "
                f"{outcome['seconds']:5.1f}s  ({len(results)}/{len(plan)})"
            )

    tasks: list[asyncio.Task] = []
    for index, request in enumerate(plan):
        tasks.append(asyncio.create_task(worker(request, index)))
        if gap and index < len(plan) - 1:
            # Jitter, so the chart looks like traffic rather than a metronome.
            await asyncio.sleep(gap * random.uniform(0.55, 1.45))

    await asyncio.gather(*tasks)

    total = time.monotonic() - started
    errors = sum(1 for r in results if not r["ok"])
    latencies = sorted(r["seconds"] for r in results)

    print(f"\n{'=' * 64}")
    print(f"  {len(results)} runs in {total / 60:.1f} min")
    print(f"  errors:      {errors} ({errors / max(len(results), 1):.0%})")
    if latencies:
        print(f"  latency p50: {latencies[len(latencies) // 2]:.1f}s")
        print(f"  latency p95: {latencies[int(len(latencies) * 0.95) - 1]:.1f}s")
    print(f"{'=' * 64}")
    print(
        "\nNow open the tracing project in LangSmith. Filter to the last hour, that view\n"
        "buckets by minute, so you should see actual shape rather than one spike.\n"
        "\nThe traces to look for: filter tag = `out_of_library`. Those are the ones where\n"
        "ARIA answered a regulatory question from memory. Module 4 fixes that."
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--runs", type=int, default=40)
    parser.add_argument("--minutes", type=float, default=10.0)
    parser.add_argument(
        "--burst",
        action="store_true",
        help="Send everything at once. Useful once, to see why spreading matters.",
    )
    parser.add_argument("--model", help="Override $ARIA_MODEL.")
    parser.add_argument("--concurrency", type=int, default=4)
    parser.add_argument("--dry-run", action="store_true", help="Print the plan, call nothing.")
    parser.add_argument(
        "--engine-warmup",
        action="store_true",
        help="High-volume repetitive failure mix for LangSmith Engine. RUN 24h BEFORE the session.",
    )
    args = parser.parse_args(argv)

    if args.engine_warmup:
        # Engine scans every 6 hours, so this has to land well before you present. Higher
        # volume, spread wider, and concurrency raised because nobody is watching it run.
        args.runs = max(args.runs, 120)
        args.minutes = max(args.minutes, 25.0)
        args.concurrency = max(args.concurrency, 6)

    from dotenv import load_dotenv

    load_dotenv(ROOT / ".env")

    if args.dry_run:
        plan = build_engine_warmup_plan(args.runs) if args.engine_warmup else build_plan(args.runs)
        for i, request in enumerate(plan, 1):
            fail = f"  [fails: {request.inject_failure}]" if request.inject_failure else ""
            print(f"{i:>3}. {request.category:<16} {request.question[:62]}{fail}")
        return 0

    asyncio.run(
        run(
            runs=args.runs,
            minutes=args.minutes,
            burst=args.burst,
            model=args.model,
            concurrency=args.concurrency,
            engine_warmup=args.engine_warmup,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
